In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df = pd.read_csv('CarDetail.csv')

In [15]:
df

name.1  year  km_driven    fuel seller_type transmission  \
0      Maruti  2014     145500  Diesel  Individual       Manual   
1       Skoda  2014     120000  Diesel  Individual       Manual   
2       Honda  2006     140000  Petrol  Individual       Manual   
3     Hyundai  2010     127000  Diesel  Individual       Manual   
4      Maruti  2007     120000  Petrol  Individual       Manual   
...       ...   ...        ...     ...         ...          ...   
7901  Hyundai  2013     110000  Petrol  Individual       Manual   
7902  Hyundai  2007     119000  Diesel  Individual       Manual   
7903   Maruti  2009     120000  Diesel  Individual       Manual   
7904     Tata  2013      25000  Diesel  Individual       Manual   
7905     Tata  2013      25000  Diesel  Individual       Manual   

                     owner  mileage  engine  max_power  torque.1  seats  \
0              First Owner    23.40    1248      74.00     190.0      5   
1             Second Owner    21.14    1498     103.52     250.0      5   
2              Third Owner    17.70    1497      78.00      12.7      5   
3              First Owner    23.00    1396      90.00      22.4      5   
4              First Owner    16.10    1298      88.20      11.5      5   
...                    ...      ...     ...        ...       ...    ...   
7901           First Owner    18.50    1197      82.85     113.7      5   
7902  Fourth & Above Owner    16.80    1493     110.00      24.0      5   
7903           First Owner    19.30    1248      73.90     190.0      5   
7904           First Owner    23.57    1396      70.00     140.0      5   
7905           First Owner    23.57    1396      70.00     140.0      5   

      selling_price  
0            450000  
1            370000  
2            158000  
3            225000  
4            130000  
...             ...  
7901         320000  
7902         135000  
7903         382000  
7904         290000  
7905         290000  

[7906 rows x 13 columns]

In [16]:
df.isnull().sum()

name.1            0
year              0
km_driven         0
fuel              0
seller_type       0
transmission      0
owner             0
mileage           0
engine            0
max_power         0
torque.1         10
seats             0
selling_price     0
dtype: int64

In [17]:
df['torque.1'].fillna(df['torque.1'].mean(), inplace=True)

In [18]:
df.isnull().sum()

name.1           0
year             0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque.1         0
seats            0
selling_price    0
dtype: int64

In [19]:
df.dtypes

name.1            object
year               int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage          float64
engine             int64
max_power        float64
torque.1         float64
seats              int64
selling_price      int64
dtype: object

# Encoding String Column

In [20]:
df['name.1'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [22]:
name = ['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel']

In [23]:
enc = OrdinalEncoder(categories=[name])

In [24]:
enc.fit_transform(df[['name.1']])

array([[0.],
       [1.],
       [2.],
       ...,
       [0.],
       [8.],
       [8.]])

In [26]:
df[['name.1']] = enc.fit_transform(df[['name.1']])
df

name.1  year  km_driven    fuel seller_type transmission  \
0        0.0  2014     145500  Diesel  Individual       Manual   
1        1.0  2014     120000  Diesel  Individual       Manual   
2        2.0  2006     140000  Petrol  Individual       Manual   
3        3.0  2010     127000  Diesel  Individual       Manual   
4        0.0  2007     120000  Petrol  Individual       Manual   
...      ...   ...        ...     ...         ...          ...   
7901     3.0  2013     110000  Petrol  Individual       Manual   
7902     3.0  2007     119000  Diesel  Individual       Manual   
7903     0.0  2009     120000  Diesel  Individual       Manual   
7904     8.0  2013      25000  Diesel  Individual       Manual   
7905     8.0  2013      25000  Diesel  Individual       Manual   

                     owner  mileage  engine  max_power  torque.1  seats  \
0              First Owner    23.40    1248      74.00     190.0      5   
1             Second Owner    21.14    1498     103.52     250.0      5   
2              Third Owner    17.70    1497      78.00      12.7      5   
3              First Owner    23.00    1396      90.00      22.4      5   
4              First Owner    16.10    1298      88.20      11.5      5   
...                    ...      ...     ...        ...       ...    ...   
7901           First Owner    18.50    1197      82.85     113.7      5   
7902  Fourth & Above Owner    16.80    1493     110.00      24.0      5   
7903           First Owner    19.30    1248      73.90     190.0      5   
7904           First Owner    23.57    1396      70.00     140.0      5   
7905           First Owner    23.57    1396      70.00     140.0      5   

      selling_price  
0            450000  
1            370000  
2            158000  
3            225000  
4            130000  
...             ...  
7901         320000  
7902         135000  
7903         382000  
7904         290000  
7905         290000  

[7906 rows x 13 columns]

In [27]:
df['name.1'].unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30.])

In [28]:
df.dtypes

name.1           float64
year               int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage          float64
engine             int64
max_power        float64
torque.1         float64
seats              int64
selling_price      int64
dtype: object

# Change data types to integer

In [29]:
df['name.1'] = df['name.1'].astype(int)

In [30]:
df.dtypes

name.1             int32
year               int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage          float64
engine             int64
max_power        float64
torque.1         float64
seats              int64
selling_price      int64
dtype: object

In [31]:
df

name.1  year  km_driven    fuel seller_type transmission  \
0          0  2014     145500  Diesel  Individual       Manual   
1          1  2014     120000  Diesel  Individual       Manual   
2          2  2006     140000  Petrol  Individual       Manual   
3          3  2010     127000  Diesel  Individual       Manual   
4          0  2007     120000  Petrol  Individual       Manual   
...      ...   ...        ...     ...         ...          ...   
7901       3  2013     110000  Petrol  Individual       Manual   
7902       3  2007     119000  Diesel  Individual       Manual   
7903       0  2009     120000  Diesel  Individual       Manual   
7904       8  2013      25000  Diesel  Individual       Manual   
7905       8  2013      25000  Diesel  Individual       Manual   

                     owner  mileage  engine  max_power  torque.1  seats  \
0              First Owner    23.40    1248      74.00     190.0      5   
1             Second Owner    21.14    1498     103.52     250.0      5   
2              Third Owner    17.70    1497      78.00      12.7      5   
3              First Owner    23.00    1396      90.00      22.4      5   
4              First Owner    16.10    1298      88.20      11.5      5   
...                    ...      ...     ...        ...       ...    ...   
7901           First Owner    18.50    1197      82.85     113.7      5   
7902  Fourth & Above Owner    16.80    1493     110.00      24.0      5   
7903           First Owner    19.30    1248      73.90     190.0      5   
7904           First Owner    23.57    1396      70.00     140.0      5   
7905           First Owner    23.57    1396      70.00     140.0      5   

      selling_price  
0            450000  
1            370000  
2            158000  
3            225000  
4            130000  
...             ...  
7901         320000  
7902         135000  
7903         382000  
7904         290000  
7905         290000  

[7906 rows x 13 columns]

# Encoding Fuel Column

In [32]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [33]:
fuel = ['Diesel', 'Petrol', 'LPG', 'CNG']

In [34]:
enc = OrdinalEncoder(categories=[fuel])

In [35]:
df[['fuel']] = enc.fit_transform(df[['fuel']])

In [38]:
df['fuel'] = df['fuel'].astype(int)

In [40]:
df['fuel'].unique()

array([0, 1, 2, 3])

# Encoding seller_type Column

In [41]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [42]:
seller = ['Individual', 'Dealer', 'Trustmark Dealer']

In [43]:
enc = OrdinalEncoder(categories=[seller])

In [44]:
df[['seller_type']] = enc.fit_transform(df[['seller_type']])

In [45]:
df['seller_type'] = df['seller_type'].astype(int)

In [46]:
df['seller_type'].unique()

array([0, 1, 2])

# Encoding transmission

In [47]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [48]:
trans = ['Manual', 'Automatic']

In [49]:
enc = OrdinalEncoder(categories=[trans])

In [50]:
df[['transmission']] = enc.fit_transform(df[['transmission']])

In [51]:
df['transmission'] = df['transmission'].astype(int)

In [52]:
df['transmission'].unique()

array([0, 1])

# Encoding Owner

In [53]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [54]:
own = ['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car']

In [55]:
enc = OrdinalEncoder(categories=[own])

In [56]:
df[['owner']] = enc.fit_transform(df[['owner']])

In [57]:
df['owner'] = df['owner'].astype(int)

In [58]:
df['owner'].unique()

array([0, 1, 2, 3, 4])

# Split data

In [59]:
X = df.drop(['selling_price'],axis=1)
Y = df['selling_price']

In [60]:
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 0)

# Build Model

In [74]:
from sklearn.linear_model import LinearRegression

# 1. Multiple Linear Regression

In [88]:
regressor = LinearRegression()

In [89]:
regressor.fit(X_train,Y_train)

LinearRegression()

In [90]:
y_pred = regressor.predict(X_test)

In [91]:
regressor.score(X_test,Y_test)

0.6805052865802712

Model is OK

In [92]:
df

name.1  year  km_driven  fuel  seller_type  transmission  owner  \
0          0  2014     145500     0            0             0      0   
1          1  2014     120000     0            0             0      1   
2          2  2006     140000     1            0             0      2   
3          3  2010     127000     0            0             0      0   
4          0  2007     120000     1            0             0      0   
...      ...   ...        ...   ...          ...           ...    ...   
7901       3  2013     110000     1            0             0      0   
7902       3  2007     119000     0            0             0      3   
7903       0  2009     120000     0            0             0      0   
7904       8  2013      25000     0            0             0      0   
7905       8  2013      25000     0            0             0      0   

      mileage  engine  max_power  torque.1  seats  selling_price  
0       23.40    1248      74.00     190.0      5         450000  
1       21.14    1498     103.52     250.0      5         370000  
2       17.70    1497      78.00      12.7      5         158000  
3       23.00    1396      90.00      22.4      5         225000  
4       16.10    1298      88.20      11.5      5         130000  
...       ...     ...        ...       ...    ...            ...  
7901    18.50    1197      82.85     113.7      5         320000  
7902    16.80    1493     110.00      24.0      5         135000  
7903    19.30    1248      73.90     190.0      5         382000  
7904    23.57    1396      70.00     140.0      5         290000  
7905    23.57    1396      70.00     140.0      5         290000  

[7906 rows x 13 columns]

In [93]:
regressor.predict([[3,2016,12000,1,0,0,1,23.4,1497,78,250,5]])

C:\Users\MrBento\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([650710.61588982])

In [95]:
y_pred = y_pred.astype(int)

In [96]:
df_preds = pd.DataFrame({'Actual': Y_test.squeeze(), 'Predicted': y_pred.squeeze()})
df_preds

Actual  Predicted
3927  430000     744762
4695  779000    1325502
4979  200000     134630
6325  800000     933783
44    390000     519118
...      ...        ...
7596  450000    1161712
2228  650000     821844
555   120000    -197202
4916  340000     309257
7222  620000     260494

[1582 rows x 2 columns]

# 2. Decision Tree Regression

In [69]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X,Y)

DecisionTreeRegressor(random_state=0)

In [70]:
y_pred = regressor.predict(X_test)

In [71]:
regressor.score(X_test,Y_test)

0.9993845138016143

Model Overfitting

In [72]:
regressor.predict([[3,2016,12000,1,0,0,1,23.4,1497,78,250,5]])

C:\Users\MrBento\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([620000.])

In [73]:
df_preds = pd.DataFrame({'Actual': Y_test.squeeze(), 'Predicted': y_pred.squeeze()})
df_preds

Actual  Predicted
3927  430000   430000.0
4695  779000   779000.0
4979  200000   190000.0
6325  800000   818750.0
44    390000   390000.0
...      ...        ...
7596  450000   450000.0
2228  650000   650000.0
555   120000   120000.0
4916  340000   340000.0
7222  620000   620000.0

[1582 rows x 2 columns]

# 3. Random Forest Regression

In [82]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(X,Y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [83]:
y_pred = regressor.predict(X_test)

In [84]:
regressor.score(X_test,Y_test)

0.9945753794320893

Model Overfitting

In [85]:
regressor.predict([[3,2016,12000,1,0,0,1,23.4,1497,78,250,5]])

C:\Users\MrBento\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([544600.])

In [86]:
df_preds = pd.DataFrame({'Actual': Y_test.squeeze(), 'Predicted': y_pred.squeeze()})
df_preds

Actual      Predicted
3927  430000  435000.000000
4695  779000  779000.000000
4979  200000  190833.333333
6325  800000  842614.285714
44    390000  411500.000000
...      ...            ...
7596  450000  455500.000000
2228  650000  602000.000000
555   120000   88670.200000
4916  340000  346200.000000
7222  620000  648000.000000

[1582 rows x 2 columns]